# Generated by Django 3.0.6 on 2020-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=64)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Email verify code')),
                ('email', models.EmailField(max_length=200, verbose_name='Email address for verifying')),
                ('send_type', models.IntegerField(choices=[(1, 'register'), (2, 'forget'), (3, 'change')], verbose_name='Type of code')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'Information of Email verifying',
                'verbose_name_plural': 'Information of Email verifying',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=65, null=True, verbose_name='Username')),
                ('password', models.CharField(max_length=15, null=True, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('Girl', 'Women'), ('Boy', 'Man')], default='Boy', max_length=10, verbose_name='Gender')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone Number')),
                ('school', models.CharField(blank=True, max_length=64, null=True, verbose_name='School')),
                ('major', models.CharField(blank=True, max_length=64, null=True, verbose_name='Major')),
                ('enrol_time', models.DateField(blank=True, null=True, verbose_name='Enroll Time')),
                ('personality', models.IntegerField(blank=True, choices=[(1, 'party'), (2, 'sports'), (3, 'game')])),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('friends', models.ManyToManyField(blank=True, related_name='_users_friends_+', to='appbackend.Users')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
            },
        ),
    ]
