# Generated by Django 3.0.6 on 2020-06-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='personality',
            field=models.IntegerField(choices=[(1, 'party'), (2, 'sports'), (3, 'game')], default=None),
        ),
    ]
