# Generated by Django 3.0.6 on 2020-06-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbackend', '0002_auto_20200617_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='personality',
            field=models.IntegerField(choices=[(1, 'party'), (2, 'sports'), (3, 'game'), (4, 'None')], default=4),
        ),
    ]
